/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package heartland.medical.center;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class MenuFrame extends javax.swing.JFrame {
    public Statement stat;
    Connection con = Koneksi.getKoneksi();
    private DefaultTableModel modeluser, modelpoli, modeldokter;

    /**
     * Creates new form MenuFrame
     */
    public MenuFrame() {
        initComponents();
        modeluser = new DefaultTableModel();
        tbluser.setModel(modeluser);
        modeluser.addColumn("Username");
        modeluser.addColumn("Nama");
        modeluser.addColumn("No Telepon");
        loadDataUser();
        
        modelpoli = new DefaultTableModel();
        tblpoli.setModel(modelpoli);
        modelpoli.addColumn("Kode Poli");
        modelpoli.addColumn("Nama Poli");
        loadDataPoli();
        
        modeldokter = new DefaultTableModel();
        tbldokter.setModel(modeldokter);
        modeldokter.addColumn("Kode Dokter");
        modeldokter.addColumn("Nama Doter");
        modeldokter.addColumn("Kode Poli");
        loadDataDokter();
    }
    
    public final void loadDataUser() {
        modeluser.getDataVector().removeAllElements();
        modeluser.fireTableDataChanged();
        try {
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM tbl_login";
            ResultSet r = s.executeQuery(sql);
            while (r.next()) {
                Object[] o = new Object[3];
                o[0] = r.getString("username");
                o[1] = r.getString("nama");
                o[2] = r.getString("no_telp");
                modeluser.addRow(o);
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Terjadi Error pada Data User");
        }
    }
    
    public final void loadDataPoli() {
        modelpoli.getDataVector().removeAllElements();
        modelpoli.fireTableDataChanged();
        try {
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM tbl_poli";
            ResultSet r = s.executeQuery(sql);
            while (r.next()) {
                Object[] o = new Object[2];
                o[0] = r.getString("kode_poli");
                o[1] = r.getString("nama_poli");
                modelpoli.addRow(o);
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Terjadi Error pada Data Poli");
        }
    }
    
    public final void loadDataDokter() {
        modeldokter.getDataVector().removeAllElements();
        modeldokter.fireTableDataChanged();
        try {
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM tbl_dokter";
            ResultSet r = s.executeQuery(sql);
            while (r.next()) {
                Object[] o = new Object[3];
                o[0] = r.getString("kode_dokter");
                o[1] = r.getString("nama_dokter");
                o[2] = r.getString("kode_poli");
                modeldokter.addRow(o);
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Terjadi Error pada Data Dokter");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbluser = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblpoli = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbldokter = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        userframe = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        dokterframe = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        pasienframe = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        poliframe = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        biayaframe = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        transaksiframe = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        laptransframe = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        lappasframe = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        tbluser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbluser);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel1)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tblpoli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblpoli);

        tbldokter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbldokter);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Poli");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Dokter");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(13, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(212, 212, 212))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Logo RS Kecil.jpg"))); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Data Master");

        userframe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Icon User.jpg"))); // NOI18N
        userframe.setText("Data User");
        userframe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userframeActionPerformed(evt);
            }
        });
        jMenu2.add(userframe);
        jMenu2.add(jSeparator1);

        dokterframe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Icon Dokter.jpg"))); // NOI18N
        dokterframe.setText("Data Dokter");
        dokterframe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dokterframeActionPerformed(evt);
            }
        });
        jMenu2.add(dokterframe);
        jMenu2.add(jSeparator2);

        pasienframe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Icon Pasien.jpg"))); // NOI18N
        pasienframe.setText("Data Pasien");
        pasienframe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasienframeActionPerformed(evt);
            }
        });
        jMenu2.add(pasienframe);
        jMenu2.add(jSeparator3);

        poliframe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Icon Poli.jpg"))); // NOI18N
        poliframe.setText("Data Poli");
        poliframe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poliframeActionPerformed(evt);
            }
        });
        jMenu2.add(poliframe);
        jMenu2.add(jSeparator4);

        biayaframe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Icon Biaya.jpg"))); // NOI18N
        biayaframe.setText("Data Biaya");
        biayaframe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biayaframeActionPerformed(evt);
            }
        });
        jMenu2.add(biayaframe);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Transaksi");

        transaksiframe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Icon Transaksi.jpg"))); // NOI18N
        transaksiframe.setText("Transaksi");
        transaksiframe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksiframeActionPerformed(evt);
            }
        });
        jMenu3.add(transaksiframe);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Laporan");

        laptransframe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Icon Laporan Transaksi.jpg"))); // NOI18N
        laptransframe.setText("Laporan Transaksi");
        laptransframe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laptransframeActionPerformed(evt);
            }
        });
        jMenu4.add(laptransframe);
        jMenu4.add(jSeparator5);

        lappasframe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Icon Laporan Pasien.jpg"))); // NOI18N
        lappasframe.setText("Laporan Pasien");
        lappasframe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lappasframeActionPerformed(evt);
            }
        });
        jMenu4.add(lappasframe);

        jMenuBar1.add(jMenu4);

        logout.setText("Logout");

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Icon Logout.jpg"))); // NOI18N
        jMenuItem9.setText("Logout");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        logout.add(jMenuItem9);

        jMenuBar1.add(logout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userframeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userframeActionPerformed
        // TODO add your handling code here:
        UserFrame fus = new UserFrame();
        fus.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_userframeActionPerformed

    private void poliframeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poliframeActionPerformed
        // TODO add your handling code here:
        PoliFrame fpol = new PoliFrame();
        fpol.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_poliframeActionPerformed

    private void dokterframeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dokterframeActionPerformed
        // TODO add your handling code here:
        DokterFrame fdok = new DokterFrame();
        fdok.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_dokterframeActionPerformed

    private void pasienframeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasienframeActionPerformed
        // TODO add your handling code here:
        PasienFrame fpas = new PasienFrame();
        fpas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pasienframeActionPerformed

    private void biayaframeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biayaframeActionPerformed
        // TODO add your handling code here:
        BiayaFrame fbi = new BiayaFrame();
        fbi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_biayaframeActionPerformed

    private void transaksiframeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksiframeActionPerformed
        // TODO add your handling code here:
        TransaksiFrame ftra = new TransaksiFrame();
        ftra.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_transaksiframeActionPerformed

    private void laptransframeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laptransframeActionPerformed
        // TODO add your handling code here:
        LaporanTransaksiFrame flapt = new LaporanTransaksiFrame();
        flapt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_laptransframeActionPerformed

    private void lappasframeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lappasframeActionPerformed
        // TODO add your handling code here:
        LaporanPasienFrame flapp = new LaporanPasienFrame();
        flapp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lappasframeActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        MainFrame fma = new MainFrame();
        fma.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem biayaframe;
    private javax.swing.JMenuItem dokterframe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuItem lappasframe;
    private javax.swing.JMenuItem laptransframe;
    private javax.swing.JMenu logout;
    private javax.swing.JMenuItem pasienframe;
    private javax.swing.JMenuItem poliframe;
    private javax.swing.JTable tbldokter;
    private javax.swing.JTable tblpoli;
    private javax.swing.JTable tbluser;
    private javax.swing.JMenuItem transaksiframe;
    private javax.swing.JMenuItem userframe;
    // End of variables declaration//GEN-END:variables
}
